# Generated by Django 4.0.2 on 2022-03-22 08:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coords', models.FloatField(default=0)),
                ('y_coords', models.FloatField(default=0)),
                ('size', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=300)),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 3, 22, 9, 49, 47, 626595))),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ObservationNormal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coords', models.FloatField(default=0)),
                ('y_coords', models.FloatField(default=0)),
                ('name', models.CharField(max_length=150)),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 3, 22, 9, 49, 47, 626595))),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
