# Generated by Django 3.2.12 on 2022-03-28 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_observationnormal_obs_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationnormal',
            name='obs_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 28, 9, 14, 42, 140255)),
        ),
        migrations.AlterField(
            model_name='observationsimple',
            name='obs_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 28, 9, 14, 42, 140255)),
        ),
    ]
