# Generated by Django 3.2.12 on 2022-03-28 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20220328_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationnormal',
            name='obs_author_name',
            field=models.CharField(default='username', max_length=150),
        ),
        migrations.AddField(
            model_name='observationsimple',
            name='obs_author_name',
            field=models.CharField(default='username', max_length=150),
        ),
        migrations.AlterField(
            model_name='observationnormal',
            name='obs_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 28, 10, 9, 1, 669592)),
        ),
        migrations.AlterField(
            model_name='observationsimple',
            name='obs_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 28, 10, 9, 1, 670589)),
        ),
    ]
