# Generated by Django 3.2.12 on 2022-03-28 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20220328_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationnormal',
            name='obs_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 28, 22, 10, 25, 393387)),
        ),
        migrations.AlterField(
            model_name='observationsimple',
            name='obs_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 28, 22, 10, 25, 394385)),
        ),
    ]
