# Generated by Django 3.2.12 on 2022-04-04 18:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0006_auto_20220328_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default=None, max_length=500, null=True)),
                ('comment_author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='observationnormal',
            name='bird_size',
            field=models.CharField(default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='observationnormal',
            name='obs_description',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='observationnormal',
            name='obs_is_simple',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='observationnormal',
            name='obs_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 4, 20, 8, 53, 358582)),
        ),
        migrations.DeleteModel(
            name='ObservationSimple',
        ),
        migrations.AddField(
            model_name='observationcomment',
            name='observation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.observationnormal'),
        ),
    ]
