# Generated by Django 3.2.12 on 2022-04-04 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20220404_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='obs_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 4, 22, 11, 24, 320315)),
        ),
    ]
