# Generated by Django 3.2.12 on 2022-04-04 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_observation_obs_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_author_id',
            new_name='author_id',
        ),
        migrations.AlterField(
            model_name='observation',
            name='obs_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 4, 22, 37, 14, 47238)),
        ),
    ]
