# Generated by Django 4.0.2 on 2022-03-22 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_observationnormal_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationnormal',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 22, 18, 47, 51, 631252)),
        ),
        migrations.AlterField(
            model_name='observationsimple',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 22, 18, 47, 51, 632249)),
        ),
    ]
