# Generated by Django 3.2.12 on 2022-04-05 09:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20220404_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='observation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='API.observation'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='obs_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 11, 12, 34, 524806)),
        ),
    ]
