# Generated by Django 3.2.12 on 2022-04-05 09:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0011_auto_20220405_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='comm_counter',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='obs_author_name',
        ),
        migrations.AlterField(
            model_name='observation',
            name='obs_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obs_author_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='observation',
            name='obs_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 11, 34, 45, 547485)),
        ),
    ]
