# Generated by Django 3.2.12 on 2022-04-05 09:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0013_auto_20220405_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='observation_id',
            new_name='observations_id',
        ),
        migrations.AlterField(
            model_name='observation',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obs_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='observation',
            name='obs_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 11, 57, 18, 996777)),
        ),
    ]
