# Generated by Django 3.2.12 on 2022-04-05 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_auto_20220405_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='observations_id',
            new_name='observation_id',
        ),
        migrations.AlterField(
            model_name='observation',
            name='obs_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 11, 58, 45, 573262)),
        ),
    ]
