# Generated by Django 3.2.12 on 2022-04-05 17:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0015_auto_20220405_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='observation',
            name='obs_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 19, 11, 30, 980465)),
        ),
    ]
