# Generated by Django 3.2.12 on 2022-04-05 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_auto_20220405_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='obs_author_name',
            field=models.CharField(default='username', max_length=150),
        ),
        migrations.AlterField(
            model_name='observation',
            name='obs_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 19, 49, 47, 962689)),
        ),
    ]
