# Generated by Django 3.2.12 on 2022-04-05 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_alter_observation_obs_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='com_author_name',
            field=models.CharField(default='username', max_length=150),
        ),
        migrations.AlterField(
            model_name='observation',
            name='obs_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 20, 28, 58, 137252)),
        ),
    ]
