# Generated by Django 3.2.12 on 2022-04-05 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_auto_20220405_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='com_author_name',
        ),
        migrations.AlterField(
            model_name='observation',
            name='obs_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 20, 43, 57, 302399)),
        ),
    ]
