# Generated by Django 3.2.12 on 2022-04-05 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_auto_20220405_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='obs_author_name',
        ),
        migrations.AlterField(
            model_name='observation',
            name='obs_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 20, 50, 15, 231972)),
        ),
    ]
