# Generated by Django 3.2.12 on 2022-04-14 09:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0021_auto_20220405_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bird_name', models.CharField(default=None, max_length=500, null=True)),
                ('bird_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='observation',
            name='obs_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 14, 11, 1, 51, 361241)),
        ),
        migrations.CreateModel(
            name='PersonalStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_count', models.IntegerField(default=0)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
