# Generated by Django 3.2.12 on 2022-04-16 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0023_auto_20220415_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='obs_is_confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='obs_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 16, 13, 30, 28, 602418)),
        ),
    ]
