# Generated by Django 3.2.12 on 2022-04-16 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0024_auto_20220416_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='obs_is_confirmed',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='obs_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 16, 15, 57, 12, 470790)),
        ),
    ]
