# Generated by Django 3.2.12 on 2022-04-16 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0025_auto_20220416_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='obs_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 16, 16, 5, 45, 995945)),
        ),
    ]
