# Generated by Django 3.2.12 on 2022-04-18 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0027_alter_observation_obs_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='obs_is_confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='obs_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 12, 24, 51, 844989)),
        ),
    ]
