# Generated by Django 3.2.12 on 2022-04-18 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0028_auto_20220418_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='obs_time',
            field=models.DateField(default=datetime.datetime(2022, 4, 18, 18, 40, 25, 557848)),
        ),
    ]
