# Generated by Django 3.2.12 on 2022-04-18 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0029_alter_observation_obs_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='obs_time',
            field=models.DateField(default=datetime.date(2022, 4, 18)),
        ),
    ]
