# Generated by Django 3.2.12 on 2022-04-19 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0030_alter_observation_obs_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='bird_beak',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='bird_color',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='bird_name',
            field=models.CharField(default='Neurčený', max_length=150),
        ),
        migrations.AlterField(
            model_name='observation',
            name='bird_size',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='obs_time',
            field=models.DateField(default=datetime.date(2022, 4, 19)),
        ),
    ]
