# Generated by Django 3.2.12 on 2022-04-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0031_auto_20220419_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='bird_recording',
            field=models.FileField(blank=True, null=True, upload_to='recording/'),
        ),
    ]
