# Generated by Django 3.2.12 on 2022-04-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0032_observation_bird_recording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='bird_recording',
            field=models.FileField(blank=True, default=None, null=True, upload_to='recording/'),
        ),
    ]
