# Generated by Django 3.2.12 on 2022-05-08 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0033_alter_observation_bird_recording'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='obs_description',
        ),
        migrations.AlterField(
            model_name='observation',
            name='obs_time',
            field=models.DateField(default=datetime.date(2022, 5, 8)),
        ),
    ]
