# Generated by Django 3.2.12 on 2022-05-10 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0034_auto_20220508_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='obs_description',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='obs_time',
            field=models.DateField(default=datetime.date(2022, 5, 10)),
        ),
    ]
